### ISSUE TITLE
Unrecognized token 'Unauthorized': was expecting ('true', 'false' or 'null')

### ISSUE THREAD

**Issue by efenderbosch** [schaloner/deadbolt-auth0-scala#1]
I'm using deadbolt while testing auth0 with a Play 2.5 app.

I've deleted a user in the dashboard and now I'm getting this error:

Unrecognized token 'Unauthorized': was expecting ('true', 'false' or 'null') @ AuthSupport.scala:111

``` scala
  def getUser(accessToken: String): Future[JsValue] = {
    val userResponse = ws.url(s"https://$domain/userinfo")
                       .withQueryString("access_token" -> accessToken)
                       .get()
    // following line is #111
    userResponse.flatMap(response => Future.successful(response.json))
  }
```

Here's the rest of the stack trace:

``` scala
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3466)
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2625)
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:854)
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:748)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3828)
at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3746)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2042)
at play.api.libs.json.jackson.JacksonJson$.parseJsValue(JacksonJson.scala:223)
at play.api.libs.json.Json$.parse(Json.scala:40)
at play.api.libs.ws.ahc.AhcWSResponse.json$lzycompute(AhcWS.scala:538)
at play.api.libs.ws.ahc.AhcWSResponse.json(AhcWS.scala:538)
at security.AuthSupport$$anonfun$getUser$1.apply(AuthSupport.scala:111)
at security.AuthSupport$$anonfun$getUser$1.apply(AuthSupport.scala:111)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
```

I'm pretty new to Play and Scala so I'm having a little trouble location where the true/false/null expectation is coming from. Any help would be appreciated.

Thanks.

**Comment by efenderbosch** [comment]
I was able to work around this by a changing getUser to detect a non-200 response:

``` scala
    userResponse.flatMap(response =>
      response.status match {
        case 200 => Future.successful(response.json)
        case 401 | 403 => Future.successful(null)
      })
```

Then `bindAndCache` simply returns null if user == null. I'm pretty sure this isn't the idiomatic  scala/play way to do this, but it works.

Any suggestions for improvement would be appreciated.

Thanks

**Comment by schaloner** [comment]
Sorry for the delay, I've been on vacation.  I'll update the examples with your workaround.

Thanks for the feedback,
Steve
